### ISSUE TITLE
Somehow broke "new folder" action in windows...

### ISSUE THREAD

**Issue by modalmodule** [SuperDisk/UGE#44] opened 2021-05-30 07:28 UTC
So I had quite a few crashes, and I think maybe it was in the process of it making backup saves, but when I tried to create a new folder in windows after, it did nothing. After hours of searching, I finally found a tut going over where the key is in regedit, and it turns out the value data had been changed from "folder" to "uge_[something]" (don't remember exactly what, sorry), that's when I was able to confirm it must've been caused by this program somehow. Super weird, and really damaging for those who don't know how to fix it. Hopefully will be easy to fix on your end though.

**Comment by SuperDisk** [comment] 2021-05-30 14:02
Hmm, I don't think this is related to HT... it never actually touches the registry. Do you have any other sort of shell extensions or stuff installed?

**Comment by SuperDisk** [comment] 2021-06-21 02:42
Since I can't reproduce this, and I'm not sure if it's related to HT, I'm going to close this issue. If it happens again, or you figure out what exactly went wrong, please reopen.

Also, as an unrelated thing, do you have any more information as to why the program was crashing in the first place? That shouldn't be happening.

**Closed as completed by SuperDisk** 2021-06-21 02:42 UTC
