### ISSUE TITLE
Access Violation Error

### ISSUE THREAD

**Issue by TakuikaNinja** [SuperDisk/UGE#1] opened 2020-01-28 01:09 UTC
This window pops up when trying to launch the application:
![image](https://user-images.githubusercontent.com/43363447/73227136-577ff880-41d7-11ea-9f44-a1a8ef06ce29.png)
Ignoring it doesn't help because the error pops up no matter what I do in the tracker.

**Comment by SuperDisk** [comment] 2020-01-28 02:15
Hey, sorry to see you got that popup. Just to verify, have you fully extracted the .zip file and ensured that all files are present when you start up the program? That error can appear when the tracker is unable to load `halt.gb` (or a few other files).

If you can, reach out to me on Discord (superdisk#5726) and I can help debug this issue.

**Comment by TakuikaNinja** [comment] 2020-01-28 02:27
I get the error even if all the files are extracted (I assume 0.3c is the current one). I'll contact you via discord, then.

**Comment by SuperDisk** [comment] 2020-02-10 06:41
Just for documentation purposes, in our discussion on Discord, @TakuikaNinja and I discovered that the issue isn't present in debug builds, which leads me to believe it's probably an out-of-bounds access or something. I'm looking into the issue. 

Meanwhile if you're getting this error, contact me and I can send you a debug build to try out.

**Comment by SuperDisk** [comment] 2020-03-20 04:01
Tentatively closing this issue because the error seems to be fixed by the removal of the offending palette code.

**Closed as completed by SuperDisk** 2020-03-20 04:01 UTC
